apiVersion: v1
kind: Service
metadata:
  name: stock-api
  namespace: widgetario
  annotations:
    mesh.traefik.io/traffic-type: "http"
spec:
  ports:
    - name: http
      port: 8080
      targetPort: api
  selector:
    app: stock-api
  type: ClusterIP