apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api-v1
  namespace: widgetario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-api
      version: v1
      ecs: m4
  template:
    metadata:
      labels:
        app: products-api
        version: v1
        ecs: m4
      annotations:
        consul.hashicorp.com/connect-inject: 'true' # create sidecar      
        consul.hashicorp.com/connect-service: products-api  # needs to match SA name
        consul.hashicorp.com/connect-service-upstreams: products-db:8097  # source:localPort
        consul.hashicorp.com/service-meta-version: v1
    spec:
      serviceAccountName: products-api
      containers:
        - name: app
          image: widgetario/products-api:java
          ports:
            - containerPort: 80
              name: api
          volumeMounts:
            - name: db-properties
              mountPath: "/app/config/db"
              readOnly: true
      volumes:
        - name: db-properties
          secret:
            secretName: products-api-db

