version: "3.7"

services:
  todo-db:
    image: diamol/postgres:11.5
    ports:
      - "5433:5432"
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - type: volume
        source: todo-db
        target: /var/lib/postgresql/data
    networks:
      - todo-net

  todo-web:
    image: diamol/ch06-todo-list
    ports:
      - "8030:80"
    environment:
      - Database:Provider=Postgres
    depends_on:
      - todo-db
    restart: always
    networks:
      - todo-net
    secrets:
      - source: postgres-connection
        target: /app/config/

networks:
  todo-net:

secrets:
  postgres-connection:
    file: ./config/

volumes:
  todo-db:
