version: "3.7"

services:
  todo-db:
    image: diamol/postgres:11.5
    ports:
      - "5433:5432"
    networks:
      - todo-net

  todo-web:
    image: diamol/ch06-todo-list
    ports:
      - "8030:80"
    environment:
      - Database:Provider=Postgres
    depends_on:
      - todo-db
    networks:
      - todo-net
    secrets:
      - source: postgres-connection
        target: /app/config/

networks:
  todo-net:

secrets:
  postgres-connection:
    file: ./config/
