apiVersion: v1
kind: Service
metadata:
  name: products-db
spec:
  ports:
    - name: tcp
      port: 5432
      targetPort: db
  selector:
    app: products-db
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: products-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-db
spec:
  selector:
    matchLabels:
      app: products-db
  template:
    metadata:
      labels:
        app: products-db
    spec:
      serviceAccountName: products-db
      containers:
        - name: db
          image: widgetario/products-db:postgres
          ports:
            - containerPort: 5432
              name: db
          env:
            - name: POSTGRES_PASSWORD
              value: ""
            - name: POSTGRES_PASSWORD_FILE
              value: /secrets/pg-password
          volumeMounts:
            - name: db-password
              mountPath: "/secrets"
              readOnly: true
      volumes:
        - name: db-password
          secret:
            secretName: products-db-password
