apiVersion: v1
kind: Secret
metadata:
  name: web-api
  namespace: widgetario
type: Opaque
stringData:
  api.json: |-
    {
      "ProductsApi": {
        "Url": "http://products-api.widgetario.traefik.mesh/products"
      },
      "StockApi": {
        "Url": "http://stock-api.widgetario.traefik.mesh:8080/stock"
      }
    }
