global:
  domain: consul
  datacenter: dc1

server:
  replicas: 1
  bootstrapExpect: 1

client:
  enabled: true

ui:
  enabled: true
  service:
    enabled: true
    type: NodePort
    additionalSpec: |         
      ports:   
        - name: ui
          port: 8500
          nodePort: 31100

connectInject:
  enabled: true

controller:
  enabled: true