apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: products-api-canary
  namespace: widgetario
spec:
  service: products-api
  backends:
  - service: products-api-v1
    weight: 70
  - service: products-api-v2
    weight: 30