apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  ports:
    - port: 8000
      targetPort: proxy
  selector:
    app: service1
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: app
          image: sixeyed/envoy-demo:service1
          env:
            - name: TARGET_HOST
              value: localhost:9000
        - name: proxy
          image: sixeyed/envoy-demo:service1-proxy
          ports:
            - containerPort: 8000
              name: proxy
