apiVersion: v1
kind: Secret
metadata:
  name: stock-api-connection
  namespace: widgetario
type: Opaque
stringData:
  POSTGRES_CONNECTION_STRING: "host=127.0.0.1 port=8097 user=postgres password=wdgtrioecsm4 dbname=postgres sslmode=disable"
