apiVersion: v1
kind: Secret
metadata:
  name: web-api
  namespace: widgetario
type: Opaque
stringData:
  api.json: |-
    {
      "ProductsApi": {
        "Url": "http://127.0.0.1:8098/products"
      },
      "StockApi": {
        "Url": "http://127.0.0.1:8099/stock"
      }
    }
