apiVersion: v1
kind: Service
metadata:
  name: products-db
spec:
  ports:
    - port: 5432
      targetPort: db
  selector:
    app: products-db
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-db
spec:
  selector:
    matchLabels:
      app: products-db
  template:
    metadata:
      labels:
        app: products-db
    spec:
      containers:
        - name: db
          image: widgetario/products-db:postgres
          ports:
            - containerPort: 5432
              name: db