apiVersion: v1
kind: Service
metadata:
  name: products-api
  namespace: widgetario
spec:
  ports:
    - port: 80
      targetPort: api
  selector:
    app: products-api
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: products-api-v1
  namespace: widgetario
spec:
  ports:
    - port: 80
      targetPort: api
  selector:
    app: products-api  
    version: v1
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: products-api-v2
  namespace: widgetario
spec:
  ports:
    - port: 80
      targetPort: api
  selector:
    app: products-api    
    version: v2
  type: ClusterIP