version: "3.7"

x-args: &args
  args:
    BUILD_NUMBER: ${BUILD_NUMBER:-0}
    BUILD_TAG: ${BUILD_TAG:-local}

services:
  access-log:
    image: ${REGISTRY:-docker.io}/${USER:-sixeyed}/access-log:ecs-c1
    build:
      context: ./access-log      
      <<: *args
    ports:
     - "80"

  image-gallery:
    image: ${REGISTRY:-docker.io}/${USER:-sixeyed}/image-gallery:ecs-c1
    build:
      context: ./image-gallery
      <<: *args
    ports:
     - "80"

  image-of-the-day:
    image: ${REGISTRY:-docker.io}/${USER:-sixeyed}/image-of-the-day:ecs-c1
    build:
      context: ./image-of-the-day
      <<: *args
    ports:
     - "80"