apiVersion: v1
kind: Secret
metadata:
  name: stock-api-connection
  namespace: widgetario
type: Opaque
stringData:
  POSTGRES_CONNECTION_STRING: "host=products-db.widgetario.svc.cluster.local port=5432 user=postgres password=wdgtrioecsm4 dbname=postgres sslmode=disable"
