global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "apod-web"
    static_configs:
      - targets: ["apod-web"]

  - job_name: "apod-log"
    static_configs:
      - targets: ["apod-log"]

  - job_name: "apod-api"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["apod-api"]