apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
spec:
  selector:    
    app: kibana
  ports:
  - name: kibana
    port: 5602
    targetPort: kibana
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
spec:
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - image: kiamol/ch13-kibana
        name: kibana
        ports:
        - containerPort: 5601
          name: kibana