apiVersion: v1
kind: Service
metadata:
  name: image-gallery
spec:
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: web
  selector:
    app: apod-web
  type: {{ .Values.serviceType }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apod-web
spec:
  selector:
    matchLabels:
      app: apod-web
  template:
    metadata:
      labels:
        app: apod-web
    spec:
      containers:
        - name: web
          image: sixeyed/image-gallery:{{ .Values.imageTag }}
          ports:
            - containerPort: 80
              name: web