apiVersion: v1
kind: Service
metadata:
  name: front-proxy
spec:
  ports:
    - port: 8800
      targetPort: 8000
  selector:
    app: front-proxy
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-proxy
spec:
  selector:
    matchLabels:
      app: front-proxy
  template:
    metadata:
      labels:
        app: front-proxy
    spec:
      containers:
        - name: app
          image: sixeyed/envoy-demo:front-proxy
