apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  ports:
    - port: 8000
      targetPort: app
  selector:
    app: service2
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
spec:
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
        - name: app
          image: sixeyed/envoy-demo:service2
          ports:
            - containerPort: 8080
              name: app
