apiVersion: v1
kind: Service
metadata:
  name: envoy-demo
spec:
  ports:
    - port: 8000
      targetPort: app
  selector:
    app: service1
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: app
          image: sixeyed/envoy-demo:service1
          ports:
            - containerPort: 8080
              name: app
          env:
            - name: TARGET_HOST
              value: service2:8000
