name: ECS-C2 CI/CD demo - v1

on:
  push:
    paths:
      - ".github/workflows/ecs-c2.yaml"
      - "episodes/ecs-c2/src/**"
  schedule:
    - cron: "0 0-7 * * *"
  workflow_dispatch:

jobs:
  ecs-c2-v1:
    runs-on: ubuntu-latest
    steps:
    
      - name: Verify
        run: |
          docker version
          docker-compose version

      - name: Checkout
        uses: actions/checkout@master

      - name: Registry login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build & push
        working-directory: ./episodes/ecs-c2/src
        run: |
          docker-compose build 
          docker-compose push
