name: ECS-C2 CI/CD demo - v2

on:
  push:
    paths:
      - ".github/workflows/ecs-c2.yaml"
      - "episodes/ecs-c2/src/**"
  workflow_dispatch:

jobs:
  ecs-c2-v2-access-log:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Registry login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker - setup buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Docker - setup layer cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Access Log
        uses: docker/build-push-action@v2
        with:
          context: ./episodes/ecs-c2/src/access-log
          file: ./episodes/ecs-c2/src/access-log/Dockerfile.v2
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          push: true
          tags: sixeyed/access-log:ecs-c2-v2

  ecs-c2-v2-image-gallery:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Registry login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker - setup buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Docker - setup layer cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Image Gallery
        uses: docker/build-push-action@v2
        with:
          context: ./episodes/ecs-c2/src/image-gallery
          file: ./episodes/ecs-c2/src/image-gallery/Dockerfile.v2
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          push: true
          tags: sixeyed/image-gallery:ecs-c2-v2

  ecs-c2-v2-image-of-the-day:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Registry login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker - setup buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Docker - setup layer cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Image of the Day
        uses: docker/build-push-action@v2
        with:
          context: ./episodes/ecs-c2/src/image-of-the-day
          file: ./episodes/ecs-c2/src/image-of-the-day/Dockerfile.v2
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          push: true
          tags: sixeyed/image-of-the-day:ecs-c2-v2

