apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-db
  namespace: widgetario
spec:
  selector:
    matchLabels:
      app: products-db
  template:
    metadata:
      labels:
        app: products-db
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: db
          image: widgetario/products-db:postgres
          ports:
            - containerPort: 5432
              name: db