apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api-v1
  namespace: widgetario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-api
      version: v1
  template:
    metadata:
      labels:
        app: products-api
        version: v1
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: api
          image: widgetario/products-api:dotnet
          ports:
            - containerPort: 80
              name: api

